### ISSUE TITLE
Touch-Interface funktioniert nicht

### ISSUE THREAD

**Issue by rodo2021** [ct-Open-Source/ct-Raspi-Radiowecker#1]
Beim start von run.sh bekomme ich diesen Fehler:
Xsession: X session started for pi at Sa 26. Okt 14:04:18 CEST 2019
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/pi/.Xauthority
xterm: cannot load font "-Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1"
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
xterm: cannot load font "-Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1"

**Comment by mecham** [comment]
Dies geschieht, wenn die Virtuelle Umgebung nicht korrekt gesetzt ist.
Der Befehl muss
python3 -m venv ~/venv
lauten, nicht, wie im Artikel
python3 -m venv venv
Die Abhängigkeiten müssen dann natürlich auch mit
pip install -r ~/alarm/requirements.txt
installiert werden.

**Comment by rodo2021** [comment]
Ich habe das Ganze noch einmal aufgesetzt, mit der Korrektur.
Aber auf dem Display ist nur die Konsole zu sehen.

Durch chmod +x run.sh und reboot funktioniert es jetzt.

**Comment by merlinschumacher** [comment]
Die Installationsanleitung im Repository habe ich soeben aktualisiert. Eine entsprechende Änderung pflege ich noch Online ein. Die erscheint dann auch im Heft.
