### ISSUE TITLE
Touch Interface startet nicht: xterm: DISPLAY is not set / locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by sirtet** [ct-Open-Source/ct-Raspi-Radiowecker#2]
Ich versuche das System auf einem Rpi2 B+ mit dem original-Raspi LCD zu installieren.
Aber das Touch UI startet nicht.
Während der Installation hatte ich einige Hänger, aber daran liegt's glaube ich nicht. Trotzdem erstmal, das waren die Probleme:

Beim Schitt `sudo pip install Mopidy-Iris Mopidy-ALSAMixer`
Hatte ich anfänglich einen Fehler:
```
ImportError: No module named setuptools
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-gWD69f/ConfigObj/
```
Nach googeln und `sudo apt-get install python-setuptools` lief es dann durch.

Auch beim Schritt `sudo pip install Mopidy-Iris Mopidy-ALSAMixer` gab es einen Fehler:
```
Building wheels for collected packages: ConfigObj
  Running setup.py bdist_wheel for ConfigObj ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-NOAPof/ConfigObj/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-4k_hpr --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for ConfigObj
  Running setup.py clean for ConfigObj
Failed to build ConfigObj
Installing collected packages: ConfigObj, Mopidy-Local-Images, Mopidy-Iris, Mopidy-ALSAMixer
  Running setup.py install for ConfigObj ... done
Successfully installed ConfigObj-5.0.6 Mopidy-ALSAMixer-1.1.1 Mopidy-Iris-3.41.2 Mopidy-Local-Images-1.0.0
```
Nach einem `sudo pip install wheel` gab es keine Fehler mehr, nur noch Meldungen ala `Requirement already satisfied:... ` aber die letzte Zeile oben sagt ja so schon, es sei alles erfolgreich installiert.

venv am falschen Ort hatte ich erst auch, aber Issue #1 habe ich gesehen, das habe ich korrigiert, selbes Ergebnis.

Jetzt zum Problem:
Nach dem Reboot startet X nur eine grafische Kommandozeile (kleinerer Font, weisser Hintergrund, Mauscursor), aber nicht das Touch Interface.

Wenn ich run.sh ausführe so wie in .xsessionrc bekomme ich die Fehlermeldung:
```
pi@raspberrypi:~/alarm $ xterm -e ~/alarm/run.sh
xterm: Xt error: Can't open display:
xterm: DISPLAY is not set
```
Keine Ahnung, vielleicht soll ich das garnicht so aufrufen? ...

Wenn ich direkt `run.sh` aufrufe, bekomme ich unterschiedliche Fehler, je nach dem wo ich das mache:
Per SSH:
``` 
pi@raspberrypi:~ $ bash alarm/run.sh
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "ct-alarm-radio.py", line 502, in <module>
    app = application()
  File "ct-alarm-radio.py", line 26, in __init__
    quit_function=self.cleanup
  File "/home/pi/alarm/gui/gui.py", line 32, in __init__
    if cursor_visible != "1": pygame.mouse.set_cursor((8,8),(0,0),(0,0,0,0,0,0,0,0),(0,0,0,0,0,0,0,0))
pygame.error: video system not initialized
```
Ok, da will es das X System wohl bei mir am entfernten Rechner (PuttY, Windows) starten, was nicht geht.

Wenn ich direkt am Rpi arbeite:
```
pi@raspberrypi:~ $ bash alarm/run.sh
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "ct-alarm-radio.py", line 502, in <module>
    app = application()
  File "ct-alarm-radio.py", line 28, in __init__
    locale.setlocale(locale.LC_ALL, self.config.setting["locale"]+".utf8")
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
hmm, irgendwo da scheint das Problem zu liegen, und nicht am anderen Display.
Ich hab `de_CH.UTF-8 UTF-8`  und `en_GB.UTF-8 UTF-8` gesetzt in raspi-config...

**Comment by sirtet** [comment]
Hmm, nach `export LC_ALL=C` startet das UI, aber es ist suuper träge...
Also liegt's schon an der Locale...
Aber wie ich das richtig mache, ist mir nicht wirklich klar. Habe verschiedene Einstellungen mit `raspi-config` probiert, en_US und de_DE dazugenommen, `none` als standard-locale, etc...

Die Trägheit, ist wohl nur der schwache Rpi?
Es ist ein B+, also Rpi1 mit ARMv6, nicht ein Rpi2.
Muss morgen mal bessere Modelle probieren, hatte gehofft für "nur" Uhr und Audio Player sollte das älteste Gerät genügen... Aber die Anleitung empfiehlt ja sogar besser einen 3er statt 2er zu nehmen.

**Comment by merlinschumacher** [comment]
Sie müssen die Locale auch noch in der clock.conf anpassen. Dort ist "de_DE" vorgegeben. In Ihrem Fall wäre "de_CH" korrekt.

Der Raspi 2 ist vermutlich gerade noch an der Grenze des Erträglichen. Ich hab mir redlich Mühe gegeben, damit Pygame performant läuft, aber bei ganz kleinen Raspis kann man nichts mehr machen.
