### ISSUE TITLE
Fehler bei sudo pip install Mopidy-Iris Mopidy-ALSAMixer

### ISSUE THREAD

**Issue by toledo2000** [ct-Open-Source/ct-Raspi-Radiowecker#5]
Der Aufruf von:
sudo pip install Mopidy-Iris Mopidy-ALSAMixer

führt bei mir zu:
Collecting Mopidy-ALSAMixer
  Downloading https://files.pythonhosted.org/packages/8d/1e/5c5602a3f3741e083678f013e8ba3fa710d1b62888837bc5f63c58c41ee1/Mopidy_ALSAMixer-1.1.1-py2.py3-none-any.whl
Collecting ConfigObj>=5.0.6 (from Mopidy-Iris)
  Downloading https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Fg3BsD/ConfigObj/

**Comment by mandree41** [comment]
genau das gleiche  habe ich auch gehabt.
allerdings habe ich keine Ahnung, warum das kommt.
ich bin nicht so fit, was linux angeht...
Das wollte ich erst noch lernen...

**Comment by rodo2021** [comment]
Ich habe es so gelöst:
vor 
sudo pip install Mopidy-Iris Mopidy-ALSAMixer
habe ich
sudo pip install --upgrade pip setuptools wheel
ausgeführt.

**Comment by toledo2000** [comment]
Danke, das hat geholfen.
